### ISSUE TITLE
Admin login form

### ISSUE THREAD

**Issue by hammadsheikh07** [EmTeaZy/artrypto#8]
Login labels should be white, font size will be changed and button color is irregular.
change the labels tag to typography for font size change and color change.
Change the button color from theme. Also the input fields need to be changed according to the color scheme

**Comment by rudeUltra** [comment]
hey i would like to contribute can you assign me this

**Comment by EmTeaZy** [comment]
> hey i would like to contribute can you assign me this

did not see your comment. the issue is resolved now.
